#!/usr/bin/env python3
"""
Generate lookup tables for sigmoid and tanh activations.

This creates properly computed LUT values for the C header file.
The tables map Q7 inputs to Q7 outputs with appropriate scaling.

Usage:
    python generate_luts.py > lut_data.txt
"""

import numpy as np


def sigmoid(x):
    """Numerically stable sigmoid."""
    return np.where(x >= 0,
                    1 / (1 + np.exp(-x)),
                    np.exp(x) / (1 + np.exp(x)))


def generate_sigmoid_lut():
    """
    Generate sigmoid lookup table.

    Input: Q7 value i in range [0, 255] representing x = (i - 128) / 32
           This maps to x in range [-4, +4]
    Output: Q7 sigmoid value in range [0, 127] representing [0, 1]
    """
    print("/* Sigmoid lookup table */")
    print("/* Input: index i where x = (i - 128) / 32.0, range [-4, +4] */")
    print("/* Output: sigmoid(x) * 127, range [0, 127] */")
    print("static const int8_t sigmoid_lut[256] = {")

    values = []
    for i in range(256):
        x = (i - 128) / 32.0  # Map to [-4, +4]
        y = sigmoid(x)
        q7_val = int(round(y * 127))
        q7_val = max(0, min(127, q7_val))  # Clamp
        values.append(q7_val)

    # Print in rows of 16
    for row in range(16):
        start = row * 16
        row_vals = values[start:start + 16]
        line = ", ".join(f"{v:4d}" for v in row_vals)
        comma = "," if row < 15 else ""
        print(f"    {line}{comma}")

    print("};")
    print()


def generate_tanh_lut():
    """
    Generate tanh lookup table.

    Input: Q7 value i in range [0, 255] representing x = (i - 128) / 64
           This maps to x in range [-2, +2]
    Output: Q7 tanh value in range [-127, 127] representing [-1, 1]
    """
    print("/* Tanh lookup table */")
    print("/* Input: index i where x = (i - 128) / 64.0, range [-2, +2] */")
    print("/* Output: tanh(x) * 127, range [-127, 127] */")
    print("static const int8_t tanh_lut[256] = {")

    values = []
    for i in range(256):
        x = (i - 128) / 64.0  # Map to [-2, +2]
        y = np.tanh(x)
        q7_val = int(round(y * 127))
        q7_val = max(-127, min(127, q7_val))  # Clamp
        values.append(q7_val)

    # Print in rows of 16
    for row in range(16):
        start = row * 16
        row_vals = values[start:start + 16]
        line = ", ".join(f"{v:4d}" for v in row_vals)
        comma = "," if row < 15 else ""
        print(f"    {line}{comma}")

    print("};")
    print()


def main():
    print("/*")
    print(" * Auto-generated lookup tables for Q7 fixed-point activations")
    print(" * Generated by generate_luts.py")
    print(" */")
    print()

    generate_sigmoid_lut()
    generate_tanh_lut()

    # Also print the inline functions
    print("/*")
    print(" * Apply sigmoid activation using lookup table")
    print(" * Input: Q7 value (will be scaled internally)")
    print(" * Output: Q7 sigmoid value in range [0, 127]")
    print(" */")
    print("static inline int8_t q7_sigmoid(int8_t x) {")
    print("    uint8_t idx = (uint8_t)(x + 128);")
    print("    return sigmoid_lut[idx];")
    print("}")
    print()
    print("/*")
    print(" * Apply tanh activation using lookup table")
    print(" * Input: Q7 value")
    print(" * Output: Q7 tanh value in range [-127, 127]")
    print(" */")
    print("static inline int8_t q7_tanh(int8_t x) {")
    print("    uint8_t idx = (uint8_t)(x + 128);")
    print("    return tanh_lut[idx];")
    print("}")


if __name__ == '__main__':
    main()
